services:
  frontend:
    image: ${DOCKER_HUB_USERNAME}/mean-crud-frontend:latest
    ports:
      - "4202:4200"
    depends_on:
      - backend

  backend:
    image: ${DOCKER_HUB_USERNAME}/mean-crud-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://mongodb:27017/mean_crud

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
