services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

  frontend:
    image: saurabhdave59/mean-crud-frontend:latest
    expose:
      - "4202"
    depends_on:
      - backend

  backend:
    image: saurabhdave59/mean-crud-backend:latest
    expose:
      - "8080"
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://mongodb:27017/mean_crud

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
