version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "4202:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/test_db
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./mongodb
      dockerfile: dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
