services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    platform: FROM --platform=linux/amd64 node:11.15
    image: saurabhdave59/mean-crud-nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: frontend
    image: saurabhdave59/mean-crud-frontend:latest
    platform: linux/amd64
    ports:
      - "4202:4202"
    environment:
      - PORT=4202
    command:
      ["sh", "-c", "ng serve --host 0.0.0.0 --port 4202 --disable-host-check"]
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: backend
    image: saurabhdave59/mean-crud-backend:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://mongodb:27017/mean_crud

  mongodb:
    container_name: mongodb
    image: mongo:latest
    platform: linux/amd64
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data
